RESOURCE_GATHERING_ENV_METRIC_KEYS = (
    "bonus_progress",
    "bonus_terminal_complete",
    "bonus_move_to_zone",
    "bonus_useful_comm",
    "bonus_first_enter_zone",
    "penalty_move",
    "penalty_comm",
    "penalty_wasted_extraction",
    "progress_score",
    "goal_wood",
    "goal_stone",
    "goal_iron",
    "collected_wood",
    "collected_stone",
    "collected_iron",
    "delta_wood",
    "delta_stone",
    "delta_iron",
    "num_comm_items",
    "useful_comm_items",
    "num_valid_extractions",
    "wasted_extractions",
    "auto_harvest_cells",
    "productive_harvesters",
    "move_steps",
    "move_toward_zone_steps",
    "first_enter_zone_count",
    "completed",
    "success",
)

__all__ = ["RESOURCE_GATHERING_ENV_METRIC_KEYS"]
