BRIDGE_BUILD_ENV_METRIC_KEYS = (
    "bonus_gap_st",
    "bonus_cc_merge",
    "bonus_y_connected",
    "bonus_terminal_clean",
    "bonus_late_quality",
    "bonus_late_quality_clean",
    "bonus_late_quality_compact",
    "bonus_late_quality_ready",
    "penalty_n_adjacent",
    "penalty_block_cost",
    "bonus_terminal_connect",
    "new_cc_merge_count",
    "new_connected_y_count",
    "new_adjacent_n_count",
    "newly_placed_block_count",
    "num_valid_probes",
    "comm_tokens",
    "success",
    "connected",
    "gap_st",
    "cc_component_count",
    "connected_y_count",
    "n_adjacent_count",
    "y_uncovered_count",
    "bonus_move_progress",
    "agent_a_target_distance",
    "agent_b_target_distance",
    "target_distance_total",
)

__all__ = ["BRIDGE_BUILD_ENV_METRIC_KEYS"]
